services:
  nginx:
    build: ./nginx
    container_name: ${PROJECT_NAME}_nginx
    restart: always
    networks:
      - ${NETWORK}
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ${DOCUMENT_ROOT}:/app
      - ../logs/nginx:/var/log/nginx/
    working_dir: /app
    depends_on: [apache]

  apache:
    build: ./httpd
    container_name: ${PROJECT_NAME}_apache
    restart: always
    networks:
      - ${NETWORK}
    volumes:
      - ${DOCUMENT_ROOT}:/app
      - ../logs/apache:/var/log/apache
    working_dir: /app


  php:
    build: ./${PHP_VERSION}
    container_name: ${PROJECT_NAME}_php
    restart: always
    networks:
      - ${NETWORK}
    volumes:
      - ${DOCUMENT_ROOT}:/app
      - ../logs/xdebug:/var/log/xdebug
    working_dir: /app
    depends_on: [apache]

  db:
    build: ./mysql
    container_name: ${PROJECT_NAME}_db
    #для версии 8.0 и выше добавляем директиву:
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - ${NETWORK}
    #    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_INITDB_SKIP_TZINFO: 1
      TZ: Europe/Moscow
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306

  node:
    build: ./node
    container_name: ${PROJECT_NAME}_node
    restart: unless-stopped
    networks:
      - ${NETWORK}
    volumes:
      - ${DOCUMENT_ROOT}:/app
    working_dir: /app
    stdin_open: true
    tty: true

  redis:
    image: arm64v8/redis:6.2.12-alpine
    container_name: ${PROJECT_NAME}_redis
    restart: always

  push-pub:
    build: ./push-server
    container_name: ${PROJECT_NAME}_push-pub
    environment:
      - MODE=pub
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: always

  push-sub:
    build: ./push-server
    container_name: ${PROJECT_NAME}_push-sub
    environment:
      - MODE=sub
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: always

networks:
  crm_apt:
    external: true