services:
  nginx:
    build: ./nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: always
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ${DOCUMENT_ROOT}:/app
      - ../logs/nginx:/var/log/nginx/
    working_dir: /app
    depends_on: [apache]

  apache:
    build: ./httpd
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    restart: always
    volumes:
      - ${DOCUMENT_ROOT}:/app
      - ../logs/apache:/var/log/apache
    working_dir: /app


  php:
    build: ./${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_php
    restart: always
    volumes:
      - ${DOCUMENT_ROOT}:/app
      - ../logs/xdebug:/var/log/xdebug
      - ../logs/xhprof:/var/log/xhprof
    working_dir: /app
    depends_on: [apache]

  db:
    build: ./mysql
    container_name: ${COMPOSE_PROJECT_NAME}_db
    #для версии 8.0 и выше добавляем директиву:
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    #    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_INITDB_SKIP_TZINFO: 1
      TZ: Europe/Moscow
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306

  node:
    build: ./node
    container_name: ${COMPOSE_PROJECT_NAME}_node
    restart: unless-stopped
    volumes:
      - ${DOCUMENT_ROOT}:/app
    working_dir: /app
    stdin_open: true
    tty: true

  xhprof-viewer:
    build: ./xhprof-viewer
    container_name: ${COMPOSE_PROJECT_NAME}_xhprof-viewer
    restart: unless-stopped
    volumes:
      - ./xhprof-viewer/viewer:/var/www/html/
      - ../logs/xhprof:/var/log/xhprof
    working_dir: /app
    ports:
      - ${XHPROF_READER_PORT}:80