services:
  nginx:
    build: ./nginx
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ${DOCUMENT_ROOT}:/app
      - ../logs/nginx:/var/log/nginx/
    working_dir: /app