services:
  nginx:
    build: ./nginx
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ${DOCUMENT_ROOT}:/app
      - ../logs/nginx:/var/log/nginx/
    working_dir: /app
    depends_on: [apache]

  apache:
    build: ./httpd
    container_name: ${PROJECT_NAME}_apache
    volumes:
      - ${DOCUMENT_ROOT}:/app
      - ../logs/apache:/var/log/apache
    working_dir: /app


  php:
    build: ./${PHP_VERSION}
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ${DOCUMENT_ROOT}:/app
    working_dir: /app
    depends_on: [apache]

  db:
    build: ./mysql
    container_name: ${PROJECT_NAME}_db
    #для версии 8.0 и выше добавляем директиву:
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    #    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_INITDB_SKIP_TZINFO: 1
      TZ: Europe/Moscow
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - 3306:3306